### ISSUE TITLE
Error when running process from different directories

### ISSUE THREAD

**Issue by petersandor** [petersandor/sysinternals#5]
```
λ sysinternals -l
fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'C:\dir\newdir\_searchdb.json'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.me.readFileSync (C:\dir\sysinternals\node_modules\full-text-search-light\node_modules\jsonfile\lib\jsonfile.js:31:26)
    at Function.FullTextSearchLight.loadSync (C:\dir\sysinternals\node_modules\full-text-search-light\index.js:43:31)
    at new Sysinternals (C:\dir\sysinternals\index.js:28:32)
    at Object.<anonymous> (C:\dir\sysinternals\index.js:103:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by petersandor** [comment]
Fixed in e7ef0ba
